# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- head0fstate-patch-1

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.dockerfile'
        tags: |
          $(tag)
    container:
        name: headofstates/iaac-web:latest
        image: hos01.azurecr.io/headofstates/iaac-web:latest
        imagepullpolicy: Always 
        
